sudo: false

language:
  - cpp

before_install:
  - pip install --user cpp-coveralls
  - sudo apt-get install libboost-thread-dev libboost-system-dev libboost-test-dev
  - sudo sed -i "s/.*boost::has_trivial_destructor.*//g"
    /usr/include/boost/lockfree/queue.hpp
  - sudo sed -i "s/.*boost::has_trivial_assign.*//g"
    /usr/include/boost/lockfree/queue.hpp

script:
  - cmake -H. -Bbuild
  - cd build
  - cmake --build .
  - ctest

after_success:
  - coveralls --root .. -E ".*CMakeFiles.*" --exclude test --exclude build
    --exclude third_party --exclude cmake --exclude README.md --exclude LICENSE
    --exclude .travis.yml
