sudo: false

language:
  - cpp

before_install:
  - pip install --user cpp-coveralls
  - sudo apt-get install libboost-thread-dev libboost-system-dev libboost-test-dev
  - sudo sed -i "s/.*boost::has_trivial_destructor.*//g"
    /usr/include/boost/lockfree/queue.hpp
  - sudo sed -i "s/.*boost::has_trivial_assign.*//g"
    /usr/include/boost/lockfree/queue.hpp

script:
  - cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug
  - cd build
  - cmake --build .
  - ctest -V

after_success:
  - coveralls --root .. -E ".*CMakeFiles.*" -E ".*test/.*" -E "build/.*"
    --exclude third_party
